version: "3"
   
services:
  postgres:
    image: postgres:11.1-alpine
    container_name: bnhs_cctms_db
    volumes:
      - bnhs_cctms_db:/var/lib/postgresql/data
    env_file:
      - .env.dev
    expose: 
      - "5432"
  backend:
    build: .
    container_name: bnhs_cctms_be
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application timeout 60
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: "on-failure"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/project/backend/cctms/static
      - media_volume:/home/project/backend/cctms/media
    ports:
      - 80:80
    restart: "on-failure"
    depends_on:
      - backend
volumes:
  bnhs_cctms_db:
    external: true
  static_volume:
  media_volume: